name: Update MTTD

on:
  push:
    branches:
      - main
    paths:
      - "update.ts"
      - ".github/workflows/update.yml"
      - "package*.json"
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - run: npx tsx update.ts
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
